
services:
  open-execution:
    build: ./openexecution
    platform: linux/amd64
    container_name: openexecution
    restart: unless-stopped
    env_file: [".env", "./environments/.env.openexecution"]
    depends_on:
      - open-execution-db
    networks:
      - ethereum
    volumes:
      - ./openexecution/scripts:/scripts
    ports:
      - 9091:9091
    logging:
      options:
        max-size: "1g"
  
  open-execution-db:
    container_name: openexecution-db
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:15.4-alpine3.18
    env_file: [".env", "./environments/.env.openexecution"]
    networks:
      - ethereum
    volumes:
      - ./openexecution/data:/var/lib/postgresql/data/
    ports:
      - "45432:45432"
    command: postgres -p 45432
    logging:
      options:
        max-size: "1g"
